trigger:
- main

variables:
  azureSubscription: 'adbaa4a2-e373-4ed1-9ba9-8ee4a8a7f2a6'
  webAppName: 'rm556974'
  vmImageName: 'nao-uso'

pool:
  name: Default

stages:
- stage: BuildAndDeploy
  displayName: 'Build e Deploy API'
  jobs:
  - job: BuildAndDeployJob
    displayName: 'Build Maven e Deploy no Azure'
    steps:
    - task: Maven@4
      displayName: 'Build com Maven'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '-DskipTests'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - script: |
        echo "Listando arquivos em target:"
        dir target
      displayName: 'Listar JAR gerado'

    - task: AzureWebApp@1
      displayName: 'Deploy JAR para Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webAppLinux'
        appName: $(webAppName)
        package: '$(System.DefaultWorkingDirectory)/target/*.jar'
